add check for being in container_deployment directory to configure

diff --git a/container_deployment/bin/configure b/container_deployment/bin/configure
--- a/container_deployment/bin/configure
+++ b/container_deployment/bin/configure
@@ -6,6 +6,11 @@ NC='\033[0m' # No Color
 #tmpfile=$(mktemp /tmp/setup.XXXXXX)
 tmpfile=./bin/setup
 # are we in an install area (where the tar was unbundled)
+if [[ "$(basename $(pwd))" != "container_deployment" ]]; then
+    echo -e "${RED}I don't see you are in a container_deployment directory - I cannot set up anything, try cd'ing to the container_deployment directory - exiting ${NC}"
+    exit 1
+fi
+
 if [[ ! -d "./web"  ]]; then
     echo -e "${RED}I don't see a ./web directory - I cannot set up anything, try cd'ing to the container deployment directory - exiting ${NC}"
     exit 1
