update debugging information on the README-INSTALL.md

diff --git a/container_deployment/bin/setup b/container_deployment/bin/setup
--- a/container_deployment/bin/setup
+++ b/container_deployment/bin/setup
@@ -13,6 +13,11 @@ function finish {
 trap finish EXIT
 
 # are we in an install area
+if [[ "$(basename $(pwd))" != "container_deployment" ]]; then
+    echo -e "${RED}I don't see you are in a container_deployment directory - I cannot set up anything, try cd'ing to the container_deployment directory - exiting ${NC}"
+    exit 1
+fi
+
 if [[ ! -d "./web"  ]]; then
     echo -e "${RED}I don't see a ./web directory - I cannot set up anything, try cd'ing to the container deployment directory - exiting ${NC}"
     exit 1
